#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/ || exit 1
