#!/usr/bin/env bash
# Install nginx
sudo apt update
sudo apt install nginx -y
sudo sed -i 's/try_files \$uri \$uri\/ =404;/return 200 "Hello World!\\\\n";/' /etc/nginx/sites-available/default
sudo service nginx restart
