#!/usr/bin/env bash
# Bash script to configure Nginx redirection

sudo apt update
sudo apt install nginx -y
sudo sed -i 's@location / {.*$@&\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}@' /etc/nginx/sites-available/default
sudo service nginx restart
