#!/usr/bin/env bash
# Bash script to configure Nginx redirection

sudo apt update
sudo apt install nginx -y
sudo rm /etc/nginx/sites-available/default
sudo nano /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # 301 redirect for /redirect_me
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF
sudo service nginx restart
