#!/usr/bin/env bash
# Bash script for configuration of a custom 404 page

sudo apt update
sudo apt install nginx -y
sudo echo "<!DOCTYPE html>
<html lang="en">
<head>
    <title>Error 404 - Not Found</title>
</head>
<body>
    <p>Ceci n'est pas une page.</p>
</body>
</html>" | sudo tee /usr/share/nginx/html/404.html
sudo echo -e "error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
