#!/bin/bash
# Bash script to configure custom 404 page
sudo apt update
sudo apt install nginx -y
echo "<!DOCTYPE html>
<html lang="en">
<head>
    <title>Error 404 - Not Found</title>
</head>
<body>
    <p>Ceci n'est pas une page.</p>
</body>
</html>" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/location \/ {/a \ \ \ \ error_page 404 /404.html;\n \ \ \ \ location = /404.html {\n \ \ \ \ \ \ \ \ root /usr/share/nginx/html;\n \ \ \ \ \ \ \ \ internal;\n \ \ \ \ }' /etc/nginx/sites-available/default
sudo service nginx restart
