#!/usr/bin/env bash
# Install customer header
sudo apt-get update
sudo apt-get install -y nginx
server_hostname=$(hostname)
echo "add_header X-Served-By $server_hostname;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo systemctl restart nginx
