#!/usr/bin/env bash
# Bash script to configure Nginx server with custom HTTP response header

sudo apt update
sudo apt install nginx -y

sudo mkdir -p /var/www/html /var/www/error
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/error/error404.html

server_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
    error_page 404 /error404.html;
    location /redirect_me {
        return 301;
    }
}"

echo "$server_config" | sudo tee /etc/nginx/sites-available/default
sudo systemctl restart nginx
