#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine

apt-get update
apt-get install -y haproxy
backend_servers="[STUDENT_ID]-web-01:80 [STUDENT_ID]-web-02:80"
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
EOF

for server in $backend_servers; do
    echo "    server $(echo $server | cut -d: -f1) $server check" >> /etc/haproxy/haproxy.cfg
done

service haproxy restart
