#!/usr/bin/env bash
# Install HAProxy

sudo apt update
sudo apt install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 18.207.2.191:80 check
    server web-02 3.90.83.114:80 check

EOF

sudo systemctl enable haproxy
sudo systemctl restart haproxy
