#!/usr/bin/env bash
# Install HAProxy

sudo apt update
sudo apt install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend www-http
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

sudo systemctl enable haproxy
sudo systemctl restart haproxy
