#!/usr/bin/env bash
# MySQL dump must contain all databases

archive_name="$(date +%m-%d-%Y).tar.gz"
name=backup.sql
mysqldump -u root -p"$1" --all-databases > $name
tar -czvf "$archive_name" backup.sql