#!/usr/bin/env bash
# script to modify hosts file 

cp /etc/hosts ~/hosts.new

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^.*facebook\.com/8.8.8.8 facebook.com/' ~/hosts.new 

cp -f ~/hosts.new /etc/hosts

rm ~/hosts.new
